package com.afrimax.paymaart.util

object Constants {
    const val TYPE = "type"
    const val OTP_FIRST_NAME = "otp_first_name"
    const val OTP_MIDDLE_NAME = "otp_middle_name"
    const val OTP_LAST_NAME = "otp_last_name"
    const val OTP_VALUE = "content"
    const val OTP_COUNTRY_CODE = "otp_country_code"
    const val OTP_TOKEN = "otp_token"
    const val OTP_EMAIL_TYPE = "email"
    const val OTP_SMS_TYPE = "sms"
    const val STAGE_DEV = "dev"
    const val STAGE_QA = "qa"
    const val INTENT_DATA_EMAIL = "intent_data_email"
    const val PRIVACY_POLICY_TYPE = "privacy_policy"
    const val TERMS_AND_CONDITIONS_TYPE = "terms_and_conditions"
    const val PRIVACY_POLICY_URL = "https://www.paymaart.net/mobile-privacy-policy"
    const val TERMS_AND_CONDITIONS_URL = "https://www.paymaart.net/mobile-customer-terms-conditions"
    const val SELECTION_PHONE_NUMBER = "selection_phone_number"
    const val SELECTION_EMAIL = "selection_email"
    const val SELECTION_PAYMAART_ID = "selection_paymaart_id"
    const val SELECTION_PASSWORD = "selection_password"
    const val SELECTION_PIN = "selection_pin"
    const val LOGIN_MODE = "login_mode"
    const val TWO_FACTOR_AUTH_TYPE = "two_factor_auth_type"
    const val TWO_FACTOR_AUTH_SETUP_TYPE = "two_factor_auth_setup_type"
    const val TWO_FACTOR_AUTH_DIRECT_TOTP_TYPE = "two_factor_auth_direct_totp_type"
    const val TWO_FACTOR_AUTH_SHARED_SECRET = "two_factor_auth_shared_secret"
    const val CUSTOM_MFA_SECRET = "custom:mfa_secret"
    const val ONBOARD_PROGRESS_SCOPE = "onboard_progress_scope"
    const val ONBOARD_PROGRESS_SCOPE_INITIAL = "onboard_progress_scope_initial"
    const val KYC_SCOPE = "kyc_scope"
    const val KYC_MALAWI_FULL = "kyc_malawi_full"
    const val KYC_CITIZENSHIP = "kyc_citizenship"
    const val KYC_STATUS_INFO_REQUIRED = "info_required"
    const val KYC_STATUS_COMPLETED = "completed"
    const val KYC_STATUS_IN_PROGRESS = "in_progress"
    const val ONBOARD_PROGRESS_SCOPE_FINAL = "onboard_progress_scope_final"

    //Shared Preferences
    const val USER_DATA_PREFS = "user_data_prefs"
    const val PREF_KEY_PAYMAART_ID = "pref_key_paymaart_id"
    const val PREF_KEY_LOGIN_MODE = "pref_key_login_mode"
}